### PR TITLE
fix "buffer size too small" exception when using long strings

### PR DESCRIPTION
**Pull request by dmfreemon**

### CODE REVIEW

**Comment by tylerjohnhughes** [comment]
This fixed my issue with the buffer size.

**Comment by braian87b** [comment]
Thanks!

**Comment by Amar1729** [comment]
@braian87b I'm pretty sure this merge fixes #27 and #67 (problems on linux) if you wanted to clean those up.

**Comment by braian87b** [comment]
Thanks!

**Comment by llamamoray** [comment]
Hi, when will this fix be released to pypi.org?

**Pull request merged**
